# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    #encoders:
    #    AppBundle\Entity\Utilisateur:
    #        algorithm: sha512
    #        encode_as_base64: false
    #        iterations: 1

    role_hierarchy:
        ROLE_PROF:     ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #internal_provider:
        #    entity:
        #        class: AppBundle:Utilisateur
        #        property: login

        ldap_provider:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: 'ou=Utilisateurs,dc=montpellier,dc=lan'
                search_dn: "cn=admin,dc=montpellier,dc=lan"
                #search_password: 'citK19c3'
                search_password: 'DreJhM34opAE3njbFbps'
                default_roles: ROLE_USER
                uid_key: uid

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            #provider: internal_provider
            #form_login:

            form_login_ldap:
                login_path: login
                check_path: login
                success_handler: redirect.after.login
                service: Symfony\Component\Ldap\Ldap
                dn_string: 'ou=Utilisateurs,dc=montpellier,dc=lan'
                query_string: '(uid={username})'
                #dn_string: 'uid={username},ou=Pedago,ou=Utilisateurs,dc=montpellier,dc=lan'
                #dn_string: 'MONTPELLIER\{username}'
            logout:
                path:   /logout
                target: /
            logout_on_user_change: true

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/prof, roles: ROLE_PROF }
        - { path: ^/, roles: ROLE_USER }
