# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_PROF:     ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        ldap_provider:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: 'OU=Pedago,OU=Utilisateurs,DC=montpellier,DC=epsi,DC=fr'
                search_dn: "CN=ADmaintain,OU=Administratif,DC=montpellier,DC=epsi,DC=fr"
                search_password: 'citK19c3'
                default_roles: ROLE_USER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            form_login_ldap:
            #http_basic_ldap:
                login_path: login
                check_path: login
                success_handler: redirect.after.login
                service: Symfony\Component\Ldap\Ldap
                dn_string: 'MONTPELLIER\{username}'
            logout:
                path:   /logout
                target: /
            logout_on_user_change: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/prof, roles: ROLE_PROF }
        - { path: ^/, roles: ROLE_USER }
