# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Utilisateur:
          algorithm: plaintext

    role_hierarchy:
        ROLE_PROF:     ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        internal_provider:
            entity:
                class: AppBundle:Utilisateur
                property: login

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: internal_provider
            form_login:
                login_path: login
                check_path: login
                success_handler: redirect.after.login
            logout:
                path:   /logout
                target: /
            logout_on_user_change: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/prof, roles: ROLE_PROF }
        - { path: ^/, roles: ROLE_USER }
