<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenceRepository extends EntityRepository
{
    public function findAllByIdAsArray($activiteId)
    {
        $query = $this->createQueryBuilder('c')
            ->where('c.idactivite = :idactivite')
            ->setParameter('idactivite', $activiteId)
            ->getQuery();

        return $query->getArrayResult();
    }
}
