<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StageintituleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageintituleRepository extends EntityRepository
{
    public function loadStageIntitules($id)
    {
        $query = $this->createQueryBuilder('si')
            ->where('si.idintitule = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $query->getResult();
    }

    public function loadStageIntitulesUser($login)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT si
                    FROM AppBundle:Stage s, AppBundle:StageIntitule si
                    WHERE s.login = :pLogin
                      AND si.idstage = s
                    ORDER BY s.annee, s.datedebut'
        )->setParameter('pLogin', $login);

        return $query->getResult();
    }
}
