<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StageintituleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageintituleRepository extends EntityRepository
{
    public function loadStageIntitules($id)
    {
        $query = $this->createQueryBuilder('si')
            ->where('si.idintitule = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $query->getResult();
    }

    public function loadStageIntitulesUser($login)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT si
                    FROM AppBundle:Stage s, AppBundle:StageIntitule si, AppBundle:Utilisateur us
                    WHERE us.login = :pLogin
                      AND s.login = us
                      AND si.idstage = s'
        )->setParameter('pLogin', $login);

        return $query->getResult();
    }
}
