<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StageintituleactiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageintituleactiviteRepository extends EntityRepository
{

    /**
     * @param $login string
     * @return /AppBundle/Entity/Stageintituleactivite[]
     */
    public function loadStageIntituleactiviteUser($login)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT sia
                    FROM AppBundle:Utilisateur us, AppBundle:Stage s, AppBundle:Stageintituleactivite sia
                    WHERE us.login = :pLogin
                      AND s.login = us
                      AND sia.idstage = s'
        )->setParameter('pLogin', $login);

        return $query->getResult();
    }
}
