<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
    public function findEtudiants($classe = null)
    {
        if ($classe != null)
        {
            $query = $this->createQueryBuilder('u')
                ->where("u.classe = :pClasse")
                ->setParameter(':pClasse', $classe)
                ->getQuery();
        }
        else {
            $query = $this->createQueryBuilder('u')
                ->where("u.classe ='B1' OR u.classe ='B2'")
                ->getQuery();
        }

        return $query->getResult();
    }
}
